name: Release Foo Tagged Template
on: workflow_dispatch

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release Foo Tagged Template npm package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code from main
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Katagawa94'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN}} 
